### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by shahabganji** [terrajobst/git-istage#12]
Hello @terrajobst 

I have installed the tool via this command `dotnet tool install git-istage -g` and I get the following error when running the `git  istage` command, or `git istage .`: 

```bash
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.get_CursorVisible()
   at GitIStage.Application.Run() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 33
   at GitIStage.Program.Main() in /home/vsts/work/1/s/src/git-istage/Program.cs:line 32
```

I just created a folder and within that, I have created a new git repository by caling `git init`, then added a simple `txt` file and add `Hello World` text inside that. then I ran `git istage . ` and I get the above mentioned error.

* worth to note that I am running Windows 7

and here is my `dotnet --info` output 

```bash
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by drewnoakes** [comment]
What terminal/console program are you using?

**Comment by shahabganji** [comment]
@drewnoakes 

I am using `Git Bash (MINGW64)` on Windows 7

**Comment by drewnoakes** [comment]
Sounds like #9. Does it work in `cmd.exe`?

**Comment by shahabganji** [comment]
That works with `cmd.exe` it also works with `git bash` as VS Code's internal terminal.

**Comment by jvlppm** [comment]
I have this same issue when running under OSX Mojave, the default terminal.

**Comment by terrajobst** [comment]
To be honest, I haven't tested Unix/macOS yet so I'd understand why that would fail. Not sure why the Windows ones fail though. I'll investigte.

**Comment by terrajobst** [comment]
Ah, just noticed you're on Win7. I'm on Win10. Maybe there is an accidental dependency somewhere that requires Win 10. I'll check.

**Comment by shahabganji** [comment]
Dear @terrajobst,

> To be honest, I haven't tested Unix/macOS yet so I'd understand why that would fail. Not sure why the Windows ones fail though. I'll investigate.

I have also checked on Mac OSX ( macOS High Sierra Version 10.13.3 ), it does not even understand the ```istage``` command.

I did the following steps: 

1. `dotnet new install -g git-istage`
2. In a git dircetory I ran : `git istage . `

and I failed with the an error message: 
```bash
git: 'istage' is not a git command. See 'git --help'.

The most similar command is
	stage
```

**Comment by tiesmaster** [comment]
@shahabganji Does the command `$ git-istage` even work (so without having git invoking `istage`)? Since that might be an [issue with .NET Global tools](https://github.com/dotnet/cli/issues/9321). I have the same on ZSH. I have solved that by following @gabrielrb [approach](https://github.com/dotnet/cli/issues/9321#issuecomment-406915716).

When I then run `istage`, from a git repository, I still get this (and mine issue #9).

**Comment by shahabganji** [comment]
I’ll take a look at the suggested approach and let you guys know about the result.

**Comment by shahabganji** [comment]
@terrajobst , @tiesmaster 

I checked the new version on my macOSX 10.13.3, and I still have the same problem, the git version is `2.16.2`, and I also checked the [suggested approach](https://github.com/dotnet/cli/issues/9321#issuecomment-406915716), however, when running `git-istage` everything works, `git istage` hits the wall though.

On my Windows 7 machine, the problem does exist too with the new version; and my git version on windows 7 is `git version 2.9.0.windows.1`.

* **PS 1:** May find it fruitful to know that on my Mac machine I have dotnet `2.2.100-preview2-009404`, and on my Windows 7 machine it is ` 2.1.403`

* **PS 2:** On Windows 7, Command Prompt  has the same problem as I described for the Mac, In powershell it works just fine and seamlessly. In Git Bash Terminal( MINGW64 ) it is just as I described [here](https://github.com/terrajobst/git-istage/issues/12#issue-370439832)

Thanks

**Comment by shahabganji** [comment]
@terrajobst , @tiesmaster 

I checked the new version on my macOSX 10.13.3, and I still have the same problem, the git version is `2.16.2`, and I also checked the [suggested approach](https://github.com/dotnet/cli/issues/9321#issuecomment-406915716), however, when running `git-istage` everything works, `git istage` hits the wall though.

On my Windows 7 machine, the problem does exist too with the new version; and my git version on windows 7 is `git version 2.9.0.windows.1`.

* **PS 1:** May find it fruitful to know that on my Mac machine I have dotnet `2.2.100-preview2-009404`, and on my Windows 7 machine it is ` 2.1.403`

* **PS 2:** On Windows 7, Command Prompt  has the same problem as I described for the Mac, In powershell it works just fine and seamlessly. In Git Bash Terminal( MINGW64 ) it is just as I described [here](https://github.com/terrajobst/git-istage/issues/12#issue-370439832)

Thanks

**Comment by shahabganji** [comment]
@terrajobst , @tiesmaster 

I checked the new version on my macOSX 10.13.3, and I still have the same problem, the git version is `2.16.2`, and I also checked the [suggested approach](https://github.com/dotnet/cli/issues/9321#issuecomment-406915716), however, when running `git-istage` everything works, `git istage` hits the wall though.

On my Windows 7 machine, the problem does exist too with the new version; and my git version on windows 7 is `git version 2.9.0.windows.1`.

* **PS 1:** May find it fruitful to know that on my Mac machine I have dotnet `2.2.100-preview2-009404`, and on my Windows 7 machine it is ` 2.1.403`

* **PS 2:** On Windows 7, Command Prompt  has the same problem as I described for the Mac, In powershell it works just fine and seamlessly. In Git Bash Terminal( MINGW64 ) it is just as I described [here](https://github.com/terrajobst/git-istage/issues/12#issue-370439832)

Thanks

**Comment by tiesmaster** [comment]
@shahabganji I'll check tomorrow on my Windows box.

**Comment by terrajobst** [comment]
> owever, when I run `git-istage` in the terminal it works, but when I run `git istage` it says no such a command found!

That's bad. I believe that's tracked by #21 now.

**Comment by tiesmaster** [comment]
I just upgraded from 0.2.2 to 0.2.29, and it's still failing under Git for Windows (using bash as shell), however, the stacktrace is now:

````
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at GitIStage.Application.Run() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 86
   at GitIStage.Program.Main() in /home/vsts/work/1/s/src/git-istage/Program.cs:line 32
````

Which makes sense, as usage of `get_CursorVisible` was removed in 9b9814e, however, `set_CursorVisible` is still there on [L106](https://github.com/terrajobst/git-istage/commit/9b9814e5185f68c79bd76304782794c46124f547#diff-71894988de713588459893ac5ad68fc6R106).

**Comment by shahabganji** [comment]
@terrajobst 
> What error do you get? I no longer call get_CursorVisible, so that must be something new then.

```bash
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at GitIStage.Application.Run() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 86
   at GitIStage.Program.Main() in /home/vsts/work/1/s/src/git-istage/Program.cs:line 32

```

**Comment by tiesmaster** [comment]
@shahabganji Ah, funny. Works in VS Code indeed. That's really odd...

**Comment by tomaszprasolek** [comment]
I also have that Exception, but when I launch git bash from path ` C:\Program Files\Git\bin\sh.exe` it works normally. Default path for git bash for windows is: `C:\Program Files\Git\git-bash.exe`
