### ISSUE TITLE
Crash with illegible exception on start

### ISSUE THREAD

**Issue by ygel** [terrajobst/git-istage#30]
I did not cut it of, this is how it prints, with a lonely `y` on the far right of the screen (for me, I moved it to the left here)

Thanks!

```
y
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_patch_from_diff(DiffHandle diff, Int32 idx)
   at LibGit2Sharp.Patch..ctor(DiffHandle diff)
   at LibGit2Sharp.Diff.<>c.<.cctor>b__36_0(DiffHandle diff)
   at LibGit2Sharp.Diff.BuildDiffResult[T](DiffHandle diff)
   at LibGit2Sharp.Diff.Compare[T](DiffModifiers diffOptions, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOption)   at GitIStage.Application.UpdateRepository() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 156
   at GitIStage.Application.InitializeScreen() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 135
   at GitIStage.Application.Run() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 97
   at GitIStage.Program.Main() in /home/vsts/work/1/s/src/git-istage/Program.cs:line 32```

**Comment by yurikus** [comment]
https://github.com/terrajobst/git-istage/pull/32 should fix this
