### ISSUE TITLE
Crash when window is taller than the diff and PageDown is pressed

### ISSUE THREAD

**Issue by ygel** [terrajobst/git-istage#31]
```
Parameter name: value
   at GitIStage.View.UpdateTopLine(Int32 value) in /home/vsts/work/1/s/src/git-istage/View.cs:line 185
   at GitIStage.Application.ScrollPageDown() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 403
   at GitIStage.Application.Run() in /home/vsts/work/1/s/src/git-istage/Application.cs:line 113
   at GitIStage.Program.Main() in /home/vsts/work/1/s/src/git-istage/Program.cs:line 32
```

**Comment by yurikus** [comment]
https://github.com/terrajobst/git-istage/pull/32 should fix this
